"""Add fulfillment models

Revision ID: a4563f14421e
Revises: 051c9a2465b7
Create Date: 2026-09-05 21:36:20.831465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4563f14421e'
down_revision: Union[str, Sequence[str], None] = '051c9a2465b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouse_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouse_inventory_id'), 'warehouse_inventory', ['id'], unique=False)
    op.create_table('fulfillment_splits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_line_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('quantity_allocated', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['quote_line_id'], ['quote_lines.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fulfillment_splits_id'), 'fulfillment_splits', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fulfillment_splits_id'), table_name='fulfillment_splits')
    op.drop_table('fulfillment_splits')
    op.drop_index(op.f('ix_warehouse_inventory_id'), table_name='warehouse_inventory')
    op.drop_table('warehouse_inventory')
    # ### end Alembic commands ###
