"""phase2_full_schema

Revision ID: d38487d04e80
Revises: a4563f14421e
Create Date: 2026-09-05 21:44:43.740910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd38487d04e80'
down_revision: Union[str, Sequence[str], None] = 'a4563f14421e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('billing_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('line_type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_schedule_id'), 'billing_schedule', ['id'], unique=False)
    op.create_table('customer_counters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_counters_id'), 'customer_counters', ['id'], unique=False)
    op.create_table('subscription_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('plan_type', sa.String(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('next_billing_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_lines_id'), 'subscription_lines', ['id'], unique=False)
    op.create_table('customer_counter_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('counter_id', sa.Integer(), nullable=False),
    sa.Column('quote_line_id', sa.Integer(), nullable=False),
    sa.Column('requested_discount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['counter_id'], ['customer_counters.id'], ),
    sa.ForeignKeyConstraint(['quote_line_id'], ['quote_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_counter_lines_id'), 'customer_counter_lines', ['id'], unique=False)
    op.add_column('products', sa.Column('billing_cycle', sa.Enum('ONE_TIME', 'MONTHLY', 'QUARTERLY', 'YEARLY', name='billingcycle'), nullable=False, server_default='ONE_TIME'))
    op.add_column('quotes', sa.Column('portal_magic_token', sa.String(), nullable=True))
    op.create_index(op.f('ix_quotes_portal_magic_token'), 'quotes', ['portal_magic_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quotes_portal_magic_token'), table_name='quotes')
    op.drop_column('quotes', 'portal_magic_token')
    op.drop_column('products', 'billing_cycle')
    op.drop_index(op.f('ix_customer_counter_lines_id'), table_name='customer_counter_lines')
    op.drop_table('customer_counter_lines')
    op.drop_index(op.f('ix_subscription_lines_id'), table_name='subscription_lines')
    op.drop_table('subscription_lines')
    op.drop_index(op.f('ix_customer_counters_id'), table_name='customer_counters')
    op.drop_table('customer_counters')
    op.drop_index(op.f('ix_billing_schedule_id'), table_name='billing_schedule')
    op.drop_table('billing_schedule')
    # ### end Alembic commands ###
